### ISSUE TITLE
`extract_boundaries()` - API error 

### ISSUE THREAD

**Issue by karishmas26** [USAID-OHA-SI/gisr#21]
error connecting to API when running `extract_boundaries()`

![image](https://github.com/USAID-OHA-SI/gisr/assets/84093378/c761239a-daad-4836-9da8-6e74b2c565ca)

**Comment by baboyma** [comment]
Fixed and merge to main. Try re-installing.

```
glamr::si_path("path_vector") |> 
  gisr::get_vcpolygons() |> 
  gisr::extract_boundaries(country = "South Africa", level = 4) |> 
  gisr::gview()
```
